### ISSUE TITLE
Core Gameplay Improvements

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [plexsoup/GWJ53#136]
In no order of priority

- advanced player movement feature (dash)
- "bullet hell" projectiles, remove hit scan weapons
- increase player move speed +++
- increase map size (design is in progress)
- establishing shot, prefight (zoom out and countdown)
- cleaning up player and enemy hitboxes
- removing reroll system, establishing "market"
- retooling game launch scene order
  - Game Start -> Junkyard -> Narrative intro -> Battle scene 1 -> mech builder
- default player mech improvement (better/more weapons)

**Comment by plexsoup** [comment]
I think we've accomplished everything on this list.
