### ISSUE TITLE
remove particle effects if Global.user_prefs["particles"] == false

### ISSUE THREAD

**Issue by plexsoup** [plexsoup/GWJ53#152]
Add a button to settings to disable particle effects.

Many particle effects are currently hidden inside AnimationPlayer animations.
Track them down and set/unset them in code.

**Comment by Haydoggo** [comment]
Opening the project folder in vscode is a good way to track stuff like this down btw
![image](https://user-images.githubusercontent.com/14885846/213624486-8445e307-9999-4716-b582-1d7c6a8e8793.png)

**Comment by Haydoggo** [comment]
Implemented with d5efe52039a72471507f4fad2b6b8aa86eefb1cf
