### ISSUE TITLE
You can lose after you defeat all enemies

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [plexsoup/GWJ53#213]
After defeating all enemies, you can still die to any remaining projectiles on screen, sending you to the junkyard.

1. Play naturally.
2. Eliminate all but 1 enemy mechs
3. Reduce player HP to 100
4. Eliminate last mech while in the path of one of its projectiles
5. Take damage from last projectile

Expected result
Player victory

Actual result
Player loses

Player impact
It can be frustrating to lose due to unfortunate positioning. Especially so when the player is locked in place after defeating the final mech.

**Comment by plexsoup** [comment]
This should be solved now.
Haven't tested it thoroughly, so it might come up again, but the player should be immune to damage after current scene declares the fight is won.
