### ISSUE TITLE
Enemies on this map default to walking upwards and get trapped in spawn on West side

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [plexsoup/GWJ53#217]
![image](https://user-images.githubusercontent.com/101430646/213848227-bcb3120e-9e56-40f2-9e13-ec09e2ff1c7d.png)

**Comment by plexsoup** [comment]
hmm. Probably related to #176.
I'll take a look.

**Comment by plexsoup** [comment]
I think this is resolved. Pretty sure.
(But the AI have other issues. They still conga line along edges.)
