### ISSUE TITLE
Generate SFX

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [plexsoup/GWJ53#53]
Generate game SFX at https://sfxr.me/ for:

To-do:

- Part buy
- hover and click sound for menu buttons
- Laser shooting
- Alt. laser shooting
- Missile shooting
- Mech walking
- shotgun shooting
- mech taking damage
- missile shooting
- missile detonating
- auto-cannon shooting
- auto-cannon impacts
- a "schwing!" sound from a 1v1 fighting game (see Kyveri ref)
- Steel door open and close
- Picking up a part in a junkyard (crunchy)
- putting a part on a mech (snap, pop, or click)
- removing a part ("")
- Special "start" sfx when entering the game for the first time (The effect should have reverb and fade for the transition to gameplay)
- Mech destroyed sound

Crowd noises (new ask)
crowd noises would really spruce up the battle scene. could we get the following noises?

- Crowd talking before a show level of crowd (this can loop during the match)
- Crowd really excited like someone scored in a sport (like when an enemy mech is destroyed)
- Crowd groans like a boxer took a bad hit (When you take too much damage or die)

**Comment by IMAFIREHAZARD** [comment]
Mechstomp.wav generated and uploaded

**Comment by IMAFIREHAZARD** [comment]
Missileshoot.wav generated and uploaded

**Comment by IMAFIREHAZARD** [comment]
Garagedoor.wav sourced from videvo.net and uploaded

**Comment by IMAFIREHAZARD** [comment]
Lasershoot.wav sourced from videvo.net and uploaded

**Comment by IMAFIREHAZARD** [comment]
Partattach.wav sourced from videvo.net and uploaded

**Comment by IMAFIREHAZARD** [comment]
Machinegunburst.wav sourced from videvo.net and uploaded

**Comment by IMAFIREHAZARD** [comment]
Engineidle.wav sourced from videvo.net and uploaded

**Comment by IMAFIREHAZARD** [comment]
Mechtrackrunning.wav sourced from videvo.net and uploaded

**Comment by plexsoup** [comment]
Choose a nice hover and click sound for menu buttons.
They can go onto res://scenes/Menus/MenuButton.tscn

**Comment by IMAFIREHAZARD** [comment]
Updated SFX task
